image: golang:latest

variables:
  REPO_NAME: gitlab.com/continuosedeliverydeveloopemnt/improvment/continuosedelivery/GodogTutorial

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get github.com/cucumber/godog/cmd/godog
  - set PATH=$PATH:$HOME/go/bin
  - echo $HOME
  - echo $PATH
  - pwd

stages:
  - integration

test-integration:
  stage: integration
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

test-acceptance:
  stage: integration
  script:
    - pwd
    - cd ../godogs
    - godog    
