image: golang:latest

 

before_script:
  - go get github.com/cucumber/godog/cmd/godog
  - set PATH=$PATH:$HOME/go/bin
  - echo $HOME
  - echo $PATH

stages:
  - integration

test-integration:
  stage: integration
  script:
    - go test

test-acceptance:
  stage: integration
  script:
    - cd ../godogs
    - godog    
