image: ubuntu

before_script:
  - set -e -x
  - apt update -y
  - apt upgrade -y
  - apt install curl -y
  - cd /usr/local
  - curl -LO https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
  - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - echo $HOME
  - echo $PATH
  - echo $GOPATH
  - cd /builds/continuosedeliverydeveloopemnt/continuosedelivery/GodogTutorial
  - pwd

stages:
  - integration

test-integration:
  stage: integration
  script:
    - cd hello
    - go test

test-acceptance:
  stage: integration
  script:
    - go get github.com/cucumber/godog/cmd/godog
    - cd ../godogs
    - godog    