image: golang:latest

variables:
  REPO_NAME: https://github.com/steinko/GodogTutorial

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME/hello

stages:
  - integration

test-integration:
  stage: integration
  script:
    - go test

test-acceptance:
  stage: integration
  script:
    - cd ../godogs
    - go godog