mage: golang:latest

variables:
  REPO_NAME: github.com/steinko/GodogTutorial

before_script:
  - go get github.com/cucumber/godog/cmd/godog
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - set PATH=$PATH:$HOME/go/bin
  - cd $GOPATH/src/$REPO_NAME/hello
  - echo $HOME
  - echo $PATH

stages:
  - integration

test-integration:
  stage: integration
  script:
    - go test

test-acceptance:
  stage: integration
  script:
    - cd ../godogs
    - godog    
